platform :ios, '11.0'

target 'LiveBlog' do
  use_frameworks!

  pod 'Alamofire', '~> 4.7.2'
  pod 'PusherSwift', '~> 6.1.0'
  pod 'PushNotifications', '~> 0.10.8'
  pod 'NotificationBannerSwift', '~> 1.6.3'
end
